ARG UBUNTU_VERS=ubuntu:noble-20241118.1

###############################################################################
# Python 312 output
###############################################################################
FROM ${UBUNTU_VERS}

SHELL ["/bin/bash", "-c", "-l"]
WORKDIR /root

COPY --from=ubu2404-plox-builder /usr/local/bin/python3.12* /usr/local/bin/
COPY --from=ubu2404-plox-builder /usr/local/lib/python3.12 /usr/local/lib/python3.12

RUN apt-get update && apt-get upgrade -yq
