ARG UBUNTU_VERS=ubuntu:noble-20241118.1

###############################################################################
# Python 311 output
###############################################################################
FROM ${UBUNTU_VERS}

SHELL ["/bin/bash", "-c", "-l"]
WORKDIR /root

COPY --from=ubu2404-plox-builder /usr/local/bin/python3.11* /usr/local/bin/
COPY --from=ubu2404-plox-builder /usr/local/lib/python3.11 /usr/local/lib/python3.11

RUN apt-get update && apt-get upgrade -yq
